-- public.category definition

-- Drop table

-- DROP TABLE public.category;

CREATE TABLE public.category (
	category_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	meta_title varchar(75) NOT NULL,
	title varchar(75) NOT NULL,
	CONSTRAINT category_pkey PRIMARY KEY (category_id),
	CONSTRAINT uk_58uwus1nnr0ha76hwpvxxy9cj UNIQUE (meta_title)
);


-- public.portal_user definition

-- Drop table

-- DROP TABLE public.portal_user;

CREATE TABLE public.portal_user (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(50) NOT NULL,
	first_name varchar(20) NULL,
	intro varchar(50) NOT NULL,
	last_login timestamp NULL,
	last_name varchar(20) NOT NULL,
	"password" varchar(10) NOT NULL,
	registered_at timestamp NOT NULL,
	CONSTRAINT portal_user_pkey PRIMARY KEY (id)
);


-- public.status_post definition

-- Drop table

-- DROP TABLE public.status_post;

CREATE TABLE public.status_post (
	status_post_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	status_name varchar(75) NOT NULL,
	CONSTRAINT status_post_pkey PRIMARY KEY (status_post_id)
);


-- public.tag definition

-- Drop table

-- DROP TABLE public.tag;

CREATE TABLE public.tag (
	tag_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(75) NOT NULL,
	CONSTRAINT tag_pkey PRIMARY KEY (tag_id),
	CONSTRAINT uk_k5g3urrxw2ym0ls8vo6xfgs65 UNIQUE (title)
);


-- public.post definition

-- Drop table

-- DROP TABLE public.post;

CREATE TABLE public.post (
	post_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp NOT NULL,
	post_content text NOT NULL,
	published_at timestamp NULL,
	summary varchar(100) NOT NULL,
	title varchar(75) NOT NULL,
	updated_at timestamp NULL,
	category_id int8 NULL,
	status_post_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT post_pkey PRIMARY KEY (post_id),
	CONSTRAINT fkedmed0aaoq2616b7di1g57f4l FOREIGN KEY (status_post_id) REFERENCES public.status_post(status_post_id),
	CONSTRAINT fkg6l1ydp1pwkmyj166teiuov1b FOREIGN KEY (category_id) REFERENCES public.category(category_id),
	CONSTRAINT fktm7nnes95ytj0le23aqbu4uj1 FOREIGN KEY (user_id) REFERENCES public.portal_user(id)
);